DROP TABLE IF EXISTS TBL_PRODUCTS;
DROP TABLE IF EXISTS TBL_PRICE;

CREATE TABLE TBL_PRODUCTS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  product_name VARCHAR(250) NOT NULL
);

CREATE TABLE TBL_PRICE (
    id_product INT NOT NULL,
    price DECIMAL(6,2) NOT NULL,
    date_begin DATE,
    date_end DATE
);

