DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS PRICE;

CREATE TABLE PRODUCT (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL
);

CREATE TABLE PRICE (
    product_id INT NOT NULL,
    price DECIMAL(6,2) NOT NULL,
    date_begin DATE,
    date_end DATE
);

